### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by matt2000** [looking-for-a-job/orderdict.py#2]
Your public repo and PyPI submission indicate that you intend for this to be broadly usable, but unless I've failed to look in the right place, you haven't provided any license with the code. If you don't have an opinion on such things, may I suggest using the MIT license?

https://opensource.org/licenses/MIT

Thanks for sharing your code!

**Comment by andrewpetrochenkov** [comment]
in the MIT license it’s inconvenient to edit the year and the author, it’s easier for me to copy a whole file without editing ))))))0 

i will use UNLICENSE, ok?

**Comment by matt2000** [comment]
Thank you!
